### ISSUE TITLE
UnhandledPromiseRejectionWarning: SequelizeEmptyResultError

### ISSUE THREAD

**Issue by skdhayal** [janKir/bgio-postgres#2]
Executing (default): SELECT "id", "gameName", "players", "setupData", "gameover", "nextRoomID", "unlisted", "state", "initialState", "log", "createdAt", "updatedAt" FROM "Games" AS "Game" WHERE "Game"."id" = 'default';
(node:27373) UnhandledPromiseRejectionWarning: SequelizeEmptyResultError

**Comment by janKir** [comment]
fixed in version 1.0.4

**Comment by skdhayal** [comment]
Thank you @janKir
